### ISSUE TITLE
Many ontologies are out of date [REDUX]

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#100]
This is the same problem as #51, it was never truly fixed

For example, DDPHENO #99 has not been updated in multiple versions

http://sparql.hegroup.org/sparql?default-graph-uri=&query=SELECT+*+WHERE+{%3Fx+owl%3AversionIRI+%3Fy}&format=text%2Fhtml&debug=on&timeout=

**Comment by e4ong1031** [comment]
The auto-update pipeline was implemented and successfully update OBO ontologies. Closing this issue.
