### ISSUE TITLE
Add OArCS to ontobee?

### ISSUE THREAD

**Issue by mjy** [OntoZoo/ontobee#103]
Our purls are resolving to OntoBee, but to blank pages.  I suspect I missed some configuration somewhere, or maybe ontobee just needs a upadate?   Other hints at getting things tweaked to work?

**Comment by yongqunh** [comment]
I don't see your OArCS ontology in OBO ontology list:
http://www.obofoundry.org/

**Comment by mjy** [comment]
Thanks! It's not in there yet.  I did see it was possible to reference
ontologies not in the foundry?

M

On Tue, Feb 14, 2017 at 1:26 PM, Yongqun Oliver He <notifications@github.com

**Comment by yongqunh** [comment]
It is possible after request. 
However, we do need to double check your ontology first. 
Have you published any paper on your work? 
Oliver

**Comment by yongqunh** [comment]
Also, have you submitted your ontology to obo-discuss?

**Comment by mjy** [comment]
Oliver-

Our paper has been accepted to Systematic Biology.

Our group has also been responsible for the HAO.

Let me know if you have other questions.

Matt

On Thu, Feb 16, 2017 at 6:41 PM, Yongqun Oliver He <notifications@github.com

**Comment by mjy** [comment]
Apologies- we have requested the OARCS namespace on obo-discuss, but we
have not announced/describe it to obo-discuss.  I'll work up an post very
soon.

**Comment by e4ong1031** [comment]
OARCS is loaded to Ontobee. Closing this issue.
