### ISSUE TITLE
Reload ENVO

### ISSUE THREAD

**Issue by pbuttigieg** [OntoZoo/ontobee#104]
Dear OntoBee Team,
Could you please reload ENVO? PURL here: http://purl.obolibrary.org/obo/envo.owl

We've made a [new release](https://github.com/EnvironmentOntology/envo/releases/tag/v2017-02-26) some days ago, but it seems the class PURLs aren't yet loaded in OntoBee.

xref to #100

**Comment by yongqunh** [comment]
Dear Pier,

As I remember, Edison recently reset our Ontobee now updates every Saturday night.

Edison,
Is this right?

Pier: If you want to have this done earlier, Edison can also do it directly…

I am now in traveling and won’t be back until next Tuesday night

Thanks,

Oliver

**Comment by pbuttigieg** [comment]
> As I remember, Edison recently reset our Ontobee now updates every Saturday night.

Thanks for the info @yongqunh - I'll wait until the 5th and report back if the PURLs still don't load. We'll try to release in sync with the OntoBee import cycle in future.

> Pier: If you want to have this done earlier, Edison can also do it directly…

We're almost at the weekend, so I think it's okay. Like I said, I'll check in on the 5th and close the issue if the import worked.

Is there any way we can enable push notification or similar to trigger an OntoBee import as soon as we release?

**Comment by cmungall** [comment]
Not sure a trigger is necessary. There are various ways to poll an 
ontology URI inexpensively. But I'm guessing it would create extra admin 
headache for ontobee admins to move to a model where different 
ontologies were loading at different times, sometimes it's easier to do 
things en masse?

**Comment by pbuttigieg** [comment]
@yongqunh 
>> As I remember, Edison recently reset our Ontobee now updates every Saturday night.
>
> Thanks for the info @yongqunh - I'll wait until the 5th and report back if the PURLs still don't load. We'll try to release in sync with the OntoBee import cycle in future.

All PURLs seem operational! xref: https://github.com/EnvironmentOntology/envo/issues/458

@cmungall 
>Not sure a trigger is necessary. There are various ways to poll an
ontology URI inexpensively. But I'm guessing it would create extra admin
headache for ontobee admins to move to a model where different
ontologies were loading at different times, sometimes it's easier to do
things en masse?

No objection to the en masse route if triggers are a headache. Now that I know the import cycle, I will be sure to release close to the harvest, so people don't get seemingly dead PURLs.
