### ISSUE TITLE
URLs that lack www prefix are not redirected correctly

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#111]
This works:

http://www.ontobee.org/ontology/HP

If I do

http://ontobee.org/ontology/HP

(www is a bit old fashioned)

I'm redirect to

http://www.ontobee.orgontology/HP

Missing a slash

**Comment by e4ong1031** [comment]
This should be fixed by now.

The link should redirect to a correct Ontobee page (you may need to refresh cache of your browser to see the effect).
