### ISSUE TITLE
Ontobee not pulling latest version of PPO

### ISSUE THREAD

**Issue by ramonawalls** [OntoZoo/ontobee#120]
e.g.
http://www.ontobee.org/ontology/PPO?iri=http://purl.obolibrary.org/obo/PPO_0002620
 says "expanding unfolded true leaves absent"

whereas the release ontology says: "expanded immature true leaves absent"

A new release was pushed about a week ago, and the PURL was updated to point to https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2017-10-20/ppo.owl

**Comment by e4ong1031** [comment]
PPO is now updated. 
We are planning to make Ontobee perform daily update and will provide better documentation of our update process soon.

Thanks,
Ed
