### ISSUE TITLE
ontobee missing

### ISSUE THREAD

**Issue by kaiiam** [OntoZoo/ontobee#124]
Greeting ontobee development team, I noticed the following error when performing the following query on the ontobee sparql end point:
```
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
SELECT DISTINCT ?input_of_inverse ?has_input_inverse
WHERE {
{?input_of_inverse owl:inverseOf <http://purl.obolibrary.org/obo/RO_0002352> . }
UNION
{?has_input_inverse owl:inverseOf <http://purl.obolibrary.org/obo/RO_0002233> . }
} 
```
which returns:

input_of_inverse | has_input_inverse
---|---|
http://purl.obolibrary.org/obo/RO_0002233 |
nodeID://b7288766	|

The class [has input](http://purl.obolibrary.org/obo/RO_0002233) has the inverse property 'input of', but it doesn't return the inverse class as expected, whereas the inverse of the class [input of](http://purl.obolibrary.org/obo/RO_0002352) is returned as expected. Perhaps this merits further investigation. 

Cheers,
Kai

**Comment by yongqunh** [comment]
This is fixed:
https://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002233
I will close the issue.

**Comment by kaiiam** [comment]
Great thanks  @yongqunh!
