### ISSUE TITLE
Error message is shown when trying to access some NCIT entities.

### ISSUE THREAD

**Issue by yy20716** [OntoZoo/ontobee#127]
It's not clear whether this issue happens due to network or browser problem but when I try to access "http://purl.obolibrary.org/obo/NCIT_C3875", Ontobee does not show anything for a while but later shows this error message.

> Error loading stylesheet: A network error occurred loading an XSLT stylesheet: http://www.ontobee.org/ontology/view/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C3875 

The similar issue arises when I also try to access http://purl.obolibrary.org/obo/NCIT_C8604. 

p.s. I don't experience this issue on other NCIT entities. Accessing some upper-level entities often takes some time but Ontobee shows the page properly in the end.

**Comment by yongqunh** [comment]
This appears fixed. I will close.
