### ISSUE TITLE
links to UBERON terms giving 500 error

### ISSUE THREAD

**Issue by jahilton** [OntoZoo/ontobee#129]
At the ENCODE portal, we provide links from our tissue samples to the ontobee page for the appropriate UBERON term. However, it seems those links are not currently working
http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0002370
http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0001114

I am also getting the same 500 error sometimes when searching on ontobee.
http://www.ontobee.org/ - no error
search 'liver' - http://www.ontobee.org/search?ontology=&keywords=liver&submit=Search+terms - no error (but also no results, which is unexpected)
select UBERON to limit search - http://www.ontobee.org/search?ontology=UBERON&keywords=liver&submit=Search+terms - 500 error

It's possible that this is the same issue seen in https://github.com/OntoZoo/ontobee/issues/127

**Comment by mcourtot** [comment]
This is working for me now, so possible it was a transient server error?

**Comment by jahilton** [comment]
All links are also working for me now. Thanks for checking it out.

**Comment by yongqunh** [comment]
That’s great. It appears a transient server error.
Oliver
