### ISSUE TITLE
OntoBee is lagging behind release of MONDO by almost 2 months

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#132]
http://www.ontobee.org/ontology/MONDO

versionIRI: http://purl.obolibrary.org/obo/mondo/releases/2018-04-15/mondo.owl

there have been several releases since then

**Comment by yongqunh** [comment]
Mondo is now updated to the latest version. The problem is that 'do_merge' of MONDO in our database is set false and therefore the auto-update script is not able to capture the changes. This has been fixed now, and the Ontobee weekly update script should be able to capture MONDO's future update.
