### ISSUE TITLE
new DUO release not loaded

### ISSUE THREAD

**Issue by mcourtot** [OntoZoo/ontobee#143]
The page at http://www.ontobee.org/ontology/duo still shows the 'old' release from December 2018. A new release was done on January 7th 2019 - this was picked up by OLS on the 8th but doesn't seem to have propagated to Ontobee yet.
Can you please check whether there is an issue with the reload?

Thanks!

**Comment by yongqunh** [comment]
Hi Melanie,

    Our Ontobee auto-update service is scheduled for every Saturday. According to your email, DUO was updated on Jan 7, which is this Monday. Ontobee is supposed to wait until this Saturday to update it.
    We have manually updated it from the server.

Thanks,
Oliver and Edison

**Comment by mcourtot** [comment]
Thanks Oliver and Edison! I thought you were doing nightly updates like OLS, thus the query.
