### ISSUE TITLE
ontobee.org seems to down with HTTP 500

### ISSUE THREAD

**Issue by dougli1sqrd** [OntoZoo/ontobee#145]
Hello,

Just within the last couple hours (2pm PST) I noticed that ontobee.org returns an error page (chrome shows the 500 error, firefox it's just a blank page).

Thanks for your help!
-Eric

**Comment by e4ong1031** [comment]
Hi Eric,

    Thank you for reporting. Ontobee is back to normal now.

Best,
Edison
