### ISSUE TITLE
Ontobee versions of EFO and MONDO are old

### ISSUE THREAD

**Issue by paolaroncaglia** [OntoZoo/ontobee#147]
Hello,
The versions of EFO and MONDO in Ontobee are out of date:

EFO:
versionIRI: http://www.ebi.ac.uk/efo/releases/2018-02-15/efo.owl
versionInfo: 2.93
(http://www.ontobee.org/ontology/EFO)
EFO releases monthly, we are now at 3.6.0 released May 15 2019;

MONDO:
versionIRI: http://purl.obolibrary.org/obo/mondo/releases/2018-12-02/mondo.owl 
http://www.ontobee.org/ontology/MONDO
There have been 2 releases since then, see https://github.com/monarch-initiative/mondo/releases
This was also reported in https://github.com/OntoZoo/ontobee/issues/132

I haven't checked other ontologies.
Many thanks,
Paola Roncaglia (EFO editor)

**Comment by yongqunh** [comment]
EFO and MONDO in Ontobee are updated now. The other ontologies should also be updated. The Ontobee servers are on the process of being transferred to new servers. We will double check this weekend to make sure. Thanks.

**Comment by paolaroncaglia** [comment]
@yongqunh 
Thank you for looking into this. I just checked, and while the MONDO version in Ontobee is now up to date, the EFO version is still 2.93 from February 2018. Could you please double-check if there's any issue and let us know. (Mentioning @zoependlington and @simonjupp for their information.)
Thanks!

**Comment by yongqunh** [comment]
It is updated in Ontobee now. It's also added to our daily update list, so later we should be able to pick it up automatically. Thanks.

**Comment by paolaroncaglia** [comment]
Thank you @yongqunh.
