### ISSUE TITLE
UBERON is out of date in Ontobee

### ISSUE THREAD

**Issue by paolaroncaglia** [OntoZoo/ontobee#148]
Hi,
The version of UBERON currently loaded in Ontobee dates back to November 2018
http://www.ontobee.org/ontology/UBERON
While the most current release is dated June 2019
https://www.ebi.ac.uk/ols/ontologies/uberon
Looking at this tracker, I see that this issue was reported more than once in the past, and that @cmungall suggested a solution in https://github.com/OntoZoo/ontobee/issues/141. 
Thanks, and kind regards,
Paola

**Comment by yongqunh** [comment]
Hi Paola,

I thought we have solved this issue. Sorry about that. Probably something occurred during our recent server updating.

Edison: could you take a close look at this issue?
Let’s talk about this in our next meeting, we need a good solution on this issue.

Thanks,
Oliver

**Comment by cmungall** [comment]
Any update?

**Comment by yongqunh** [comment]
UBERON is up to date. Chris suggestion on inserting a triple to the ontology whenever Ontobee updates is a good idea. We will do it after a current task is handled. Thanks.
