### ISSUE TITLE
Ontobee is returning obsolete search results for PECO

### ISSUE THREAD

**Issue by cooperl09** [OntoZoo/ontobee#151]
HI
I was recently contacted by a confused user who has been getting odd search results on Ontobee.  The Plant Environment Ontology (EO) was renamed the Plant Experimental Conditions Ontology (PECO) in October 2017, to better reflect the content and avoid confusion with the Environment Ontology (ENVO).  Although the EO no longer shows up on the Ontology table, it comes back on search results. For example, if you search for soil pH, the top response is to the deprecated term in EO: http://www.ontobee.org/ontology/EO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FEO_0007058. 
Can you remove the old EO from the search results?

**Comment by e4ong1031** [comment]
Hi @cooperl09 

    The EO ontology terms should not show up in the search result anymore.

Thanks

**Comment by cooperl09** [comment]
Thanks for fixing that

**Comment by cooperl09** [comment]
@lbtgnn68
