### ISSUE TITLE
Links to CL ontology not working

### ISSUE THREAD

**Issue by fbastian** [OntoZoo/ontobee#165]
Links such as http://purl.obolibrary.org/obo/CL_0000576 are not working. Even from the search results the links are not working, e.g., http://www.ontobee.org/search?ontology=&keywords=CL_0000094&submit=Search+terms

**Comment by yongqunh** [comment]
This appears fine now from my computer. I am going to close it. Please inform if this still does not work. Thanks.

**Comment by fbastian** [comment]
Indeed it works now. Thanks for checking.
