### ISSUE TITLE
PATO browsing broken

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#166]
http://www.ontobee.org/ontology/FOODON?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001241
links to http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0001241 which gives Term Not Found.

**Comment by alanruttenberg** [comment]
Actually PATO just looks broken altogether. Searches for terms always failing for me.

**Comment by yongqunh** [comment]
This issue should be solved now.
