### ISSUE TITLE
Detailed statistics empty for Chebi

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#167]
http://www.ontobee.org/ontology/CHEBI 
click on detailed statistics
All entries are 0

**Comment by michaelcooke** [comment]
Hi Alan,

I'm Michael Cooke, a research assistant with the He Lab in charge of ongoing support for Ontobee. Thank you for opening this issue and letting us know about this problem.

I've taken a look on our end and determined that our daily updater had some trouble downloading the ontology for some reason. I've manually downloaded and uploaded the ontology, and will be monitoring the issue closely for the next few days.

I'm going to ask Oliver to close this issue for now, but feel free to re-open if the problem crops up again.
