### ISSUE TITLE
DRON is not loaded

### ISSUE THREAD

**Issue by linikujp** [OntoZoo/ontobee#171]
Hi the DRON is not loaded correctly. I saw 0 classes, properties and so on.

**Comment by paolaroncaglia** [comment]
Hi @yongqunh and @linikujp ,

EFO is also not accessible in Ontobee at the moment: empty stats and term search not working. The linked owl file is ok though. I noticed other similar, recent tickets, like https://github.com/OntoZoo/ontobee/issues/174. Could you please look into this? 

Thank you in advance.

**Comment by daniwelter** [comment]
Same problem also for HANCESTRO. I'd appreciate if you could look into it because I think broken purl links stop the refresh in OLS, which means our latest release isn't picked up.

**Comment by yongqunh** [comment]
both DRON and HANCESTRO should be fixed by now.
