### ISSUE TITLE
Unit of misurement ontology (UO) appears empty

### ISSUE THREAD

**Issue by nmatasci-eitm** [OntoZoo/ontobee#176]
The UO ontology https://www.ontobee.org/ontology/UO doesn't show any terms and direct links to terms go to an error page (http://purl.obolibrary.org/obo/UO_0000063). Similarly, the excel and tsv export result in files with only the header. However, the OWL file is correct
![image](https://user-images.githubusercontent.com/83838330/171963646-fc71649e-091f-4f07-9341-5b85650687d1.png)

**Comment by yongqunh** [comment]
This is fixed now.
