### ISSUE TITLE
PATO terms are not resolvable

### ISSUE THREAD

**Issue by relleoML** [OntoZoo/ontobee#177]
Dear OBO team,

there seem to be issues related to the PATO ontology. Neither terms are resolved, nor does the ontology itself contain anything.
e.g. https://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0001522 results in
![image](https://user-images.githubusercontent.com/101594944/173523049-dee3bec5-8468-4c4c-a454-57ea8b2ef83c.png)

PATO statistics yields:
![image](https://user-images.githubusercontent.com/101594944/173522901-48d0bb39-56f2-42fe-a5cb-6218621dd300.png)

Issue is probably related to #176

**Comment by yongqunh** [comment]
This is fixed now.
