### ISSUE TITLE
BioAssay Ontology (BAO) Download Link is broken

### ISSUE THREAD

**Issue by donpellegrino** [OntoZoo/ontobee#180]
For the Ontobee BAO entry at https://ontobee.org/ontology/BAO, the Download link is https://raw.githubusercontent.com/BioAssayOntology/BAO/master/BAO/bao_complete_merged.owl which gives a 404.

**Comment by yongqunh** [comment]
Updated to:
https://raw.githubusercontent.com/BioAssayOntology/BAO/master/bao_complete_merged.owl

It appears working now:
https://ontobee.org/ontology/BAO
