### ISSUE TITLE
PCL no longer appearing in Ontobee

### ISSUE THREAD

**Issue by shawntanzk** [OntoZoo/ontobee#181]
Pretty sure it was in there before, but it don't find it there now (https://ontobee.org/ontology/pcl does not resolve). 
In case its needed: https://obofoundry.org/ontology/pcl.html 
Thanks!

**Comment by yongqunh** [comment]
It's here now:
https://ontobee.org/ontology/PCL

Thanks, Oliver

**Comment by shawntanzk** [comment]
Thanks heaps! really appreciate it :)
