### ISSUE TITLE
Change contact for FYPO

### ISSUE THREAD

**Issue by manulera** [OntoZoo/ontobee#182]
Hello,

I am writing regarding FYPO ontology: https://ontobee.org/ontology/FYPO

The contact email should be changed to ucbtml2@ucl.ac.uk, as the person with that email no longer works for FYPO.

Tagging @ValWood, project leader, to confirm that she approves this request.

**Comment by yongqunh** [comment]
Updated as requested:
https://ontobee.org/ontology/FYPO

**Comment by manulera** [comment]
Thanks
