### ISSUE TITLE
Ontofox Bug: Some ontologies not updating/importing

### ISSUE THREAD

**Issue by cmrn-rhi** [OntoZoo/ontobee#187]
I have been trying to update some import files using Ontofox and it's failing to import terms it has successfully imported in the past. This includes terms from APOLLO_SV, ERO, OBI, NCIT, and NCBITaxon. I search a few terms from each of these ontologies and they show up in Ontobee, except for APOLLO_SV terms (and these terms did show up in EBI).

I've included input files, output files, and pdfs of the ontofox web output in the attached zip file.

[2023-01-03_ontofox issue 187.zip](https://github.com/OntoZoo/ontobee/files/10340631/2023-01-03_ontofox.issue.187.zip)

**Comment by yongqunh** [comment]
interesting. it appears NCBITaxon is working. I tested some examples and it worked fine. 
I would suggest that you first simplify your operation by using a small number of input, and then slowing adding more terms to your input. hopefully you can find where the issue is. 
Best,

**Comment by cmrn-rhi** [comment]
I tried rerunning the NCBITaxon file (unchanged) and also had no issue today, so not sure what changed it does appear NCBITaxon is now fine. However, running the general file still failed to import the APOLLO_SV, ERO, and NCIT (removed OBI as it was importing from ERO in this case).

**Comment by cmrn-rhi** [comment]
Tried importing again, and APOLLO_SV terms were showing up but without annotations, and some of the NCIT terms (like Gene Product - NCIT_C26548) are there now while others aren't (Disease, Disorder or Finding - NCIT_C7057).

**Comment by yongqunh** [comment]
The NCBI and APOLLO_SV have been updated in Ontobee. please try ago. 
The ERO appears to have issue: http://purl.obolibrary.org/obo/ero.owl .

**Comment by cmrn-rhi** [comment]
Thank you. I reran after removing ERO and everything worked except NCIT - it was still not importing. 
[2023-01-21_ontofox issue 187 ERO removed.zip](https://github.com/OntoZoo/ontobee/files/10473191/2023-01-21_ontofox.issue.187.ERO.removed.zip)

**Comment by yongqunh** [comment]
I see. NCIT appears to be fine in Ontobee. Sometimes Ontofox stopped working when there are too many terms to extract. You can test this by reducing the number of NCIT terms in your process.

**Comment by cmrn-rhi** [comment]
I tried isolating it and ran only the NCIT ones in a new ontofox generated file and the same thing happened. However, I scanned through and found some "tabs" instead of spaces and removed those. It worked fine after that.

Thank you for your time, I consider this issue resolved.
