### ISSUE TITLE
Reload GENEPIO

### ISSUE THREAD

**Issue by cmrn-rhi** [OntoZoo/ontobee#191]
GENEPIO doesn't appear to be loading on ontobee, can that be remedied?
It passed a "make reason" reasoner test and "riot" command check on our end, but if there are any issues we should address please let us know.

**Comment by yongqunh** [comment]
GENEPIO is now loaded on Ontobee:
https://ontobee.org/ontology/GENEPIO
thanks,

**Comment by cmrn-rhi** [comment]
Ontobee isn't showing GENEPIO results as of 2023-09-22

**Comment by yongqunh** [comment]
Back now:
https://ontobee.org/ontology/GENEPIO
