### ISSUE TITLE
MS ontology not working in Ontobee

### ISSUE THREAD

**Issue by edeutsch** [OntoZoo/ontobee#194]
Hi, it looks like attempts to browse the MS ontology has stopped working in OntoBee, e.g.:

https://ontobee.org/ontology/MS?iri=http://purl.obolibrary.org/obo/MS_1000881

Something still shows up here:
https://ontobee.org/ontology/MS

But clicking on any of the terms listed there yields an error.

Would you fix?

**Comment by yongqunh** [comment]
Done. Thanks.

**Comment by edeutsch** [comment]
thank you!

**Comment by Hannah-Doerpholz** [comment]
Sorry to add onto this but it looks like the problem with the MS ontology appeared again. The exact same behaviour can still be seen if I try clicking any MS terms
