### ISSUE TITLE
The main http://www.ontobee.org is down?

### ISSUE THREAD

**Issue by yarikoptic** [OntoZoo/ontobee#196]
Our tests in dandi started to fail due to timeouts trying to connect, see e.g. https://github.com/dandi/dandi-cli/actions/runs/8151763260/job/22280140951 . Can't reach http://www.ontobee.org/ in the browser locally either

**Comment by yarikoptic** [comment]
seems to be back online
![image](https://github.com/OntoZoo/ontobee/assets/39889/2f46fbcc-8ff8-4582-bf31-b838f3e35d90)

**Comment by yongqunh** [comment]
Thanks!
