### ISSUE TITLE
Server is down again?

### ISSUE THREAD

**Issue by yarikoptic** [OntoZoo/ontobee#199]
![image](https://github.com/OntoZoo/ontobee/assets/39889/4c0b6e68-b02c-4c2f-9f05-286c4075f58f)

prior occurrence
- https://github.com/OntoZoo/ontobee/issues/196

FWIW I had been similarly cursed recently. Blaming wsgi.  Unlikely the same but here is more info:
- https://github.com/neuronets/nobrainer/issues/304#issuecomment-2012117565

**Comment by cmungall** [comment]
Seems to be fixed now

**Comment by yongqunh** [comment]
Yes. It's fixed. Thanks!
