### ISSUE TITLE
ObjectProperty hierarchy not showing

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#29]
http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0002202

should have parents & children

**Comment by cmungall** [comment]
Any progress on this?

@ontoden, I don't quite understand your comment - was it directed at me?

In answer I would reply generally that ontobee should follow http://www.w3.org/TR/owl2-mapping-to-rdf/ and render things in OWL manchester syntax or similar as far as possible, like Protege. 

At least: show parents or a subproperty hierarchy

See:

![screen shot 2015-03-09 at 4 13 51 pm](https://cloud.githubusercontent.com/assets/50745/6566481/52c3b132-c677-11e4-8347-b754fd0aa800.png)

**Comment by cmungall** [comment]
My guess that in some cases ontobee somehow fails to recognize that the URI is for an OP and defaults into displaying as an individual.

E.g. this works:
http://purl.obolibrary.org/obo/RO_0002132

My hypothesis is that if the OP has any Characteristics, it renders incorrectly. This is because in the mapping of OWL to RDF, the rdf:type is not directly to owl:ObjectProperty, but to the particular characteristic (e.g. owl:TransitiveProperty). Is this what you were saying @ontoden?

**Comment by e4ong1031** [comment]
This issue is now fixed.

http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0002202

**Comment by ontoden** [comment]
Good for you, Edison! Thanks!

**Comment by cmungall** [comment]
Thanks Edison!

By the way, did you know you can close tracker items with a commit message? E.g. in your commit if you say "Fixes #29" then a link to the diff will be present in this tracker item. This is a really useful feature for other ontobee developers
