### ISSUE TITLE
Class/usage not shown on instance page

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#33]
E.g. http://purl.obolibrary.org/obo/IAO_0000227 "terms merged" doesn't show it's parent 'has obsolescence reason' .

Also uses in this ontology is not shown. For example http://purl.obolibrary.org/obo/IAO_0000103 'failed exploratory term' has a number of uses among the obsolete terms in OBI.

**Comment by e4ong1031** [comment]
This issue is fixed in the new beta version of ontobee. http://beta.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000227
