### ISSUE TITLE
OBI coming up empty

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#36]
Clicking on any term at http://www.ontobee.org/browser/index.php?o=OBI yields: 

We are sorry that your request did not return any expected result. Here is a list of possible reasons:

Your requested term has been deprecated
The ontology that contains the term has not been updated
Whoops! Our program has an unhandled and unexpected error in processing your request.
If you think that you reached this page in error, or you have any request or concern, you may contact us by:

Raise the issue in the Ontobee-discuss Google Group (Note: Recommended if you want fastest reply):
Leave a message at https://groups.google.com/forum/#!forum/ontobee-discuss, or
Directly send an email to: ontobee-discuss@googlegroups.com 
Note: You are welcome to join the group, and it is open to everyone:-)
Submit a bug report or request a new feature at: https://sourceforge.net/p/ontobee/feature-requests/
For OBO Foundry related questions, contact: http://code.google.com/p/obo-foundry-operations-committee/
Email Oliver He at: 
Thank you.

**Comment by ontoden** [comment]
OK. I was trying to upload PR.
I think I broke the rdf triple store again.
Let me try to fix it.
Oliver

**Comment by ontoden** [comment]
It’s back now.
Oliver

From: He, Yongqun
Sent: Thursday, February 12, 2015 2:12 PM
To: 'ontoden/ontobee'; ontoden/ontobee
Subject: RE: [ontobee] OBI coming up empty (#36)

OK. I was trying to upload PR.
I think I broke the rdf triple store again.
Let me try to fix it.
Oliver
