### ISSUE TITLE
Obsolete ENVO classes retrieved 

### ISSUE THREAD

**Issue by pbuttigieg** [OntoZoo/ontobee#43]
Dear OntoBee team,

Some of ENVO's obsolete classes are retrieved in the general search, but it's not really made clear that they are obsolete. 

For example:

 `
  

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/ENVO_00002993">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Tropical humid forests</rdfs:label>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO:00002993</oboInOwl:id>
        <oboInOwl:consider rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO:01000228</oboInOwl:consider>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
    `
Perhaps checking for <owl:deprecated> boolean = true or the presence of consider or replaced by annotation properties may be a good way to filter these.

**Comment by cmungall** [comment]
I recommend doing something like ontobee, e.g. rendering with strikethrough

**Comment by alanruttenberg** [comment]
I would suggest not filtering by default but instead a) show a clearly visible visual indicator with the term(eg strike through and badge on page) and b) have any obsolete terms sorted to the end of results. Perhaps have a cookie-remembered checkbox asking for them not to be shown, not checked by default. 

The principle is to ensure that the principle that terms don't just disappear I reinforced.  In addition obsolete terms may have useful information such as deprecation reason or suggested alternatives. 

The suggested checkbox is for people who are familiar enough that they understand what they will be missing. Remember the state by cookie is to avoid irritating users that choose this option.

**Comment by ontoden** [comment]
There are several issues related to Pier’s ENVO example:



<owl:Class rdf:about="http://purl.obolibrary.org/obo/ENVO_00002993">

    <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Tropical humid forests</rdfs:label>

    <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO</oboInOwl:hasOBONamespace>

    <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO:00002993</oboInOwl:id>

    <oboInOwl:consider rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO:01000228</oboInOwl:consider>

    <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>

</owl:Class>

Here the classification of the term as deprecated is different from classifying it as a subclass of an “obsolete” class. It provides an Boolean value. Ontobee has not handled this issue yet.

Another issue is how to clearly show it’s an obsolete or deprecated class, such as using the strikethrough sign.

I have discussed with Edison. He will be working on it soon. Once an outcome is available, we will inform it and ask for feedback.

Oliver

**Comment by cmungall** [comment]
owl:deprecated is standard

**Comment by mcourtot** [comment]
Could the obsolete classes also be pushed to the bottom of the list when
doing a general search?

**Comment by ontoden** [comment]
OK. Edison just finished another update. The new update works as shown below:

For example, if we search for “forest” in the Ontobee general search (shown on the cover page), we get:
http://www.ontobee.org/browser/search.php?ontology=ENVO&keywords=forest&Submit2=Search+terms

The deprecated (or obsolete) terms are listed at the bottom of the page like this:
[cid:image001.jpg@01D0CF88.01A692A0]

If we click on the “Show Deprecated Terms”, we can see:
[cid:image002.jpg@01D0CF88.01A692A0]

Here all the deprecated terms are crossed with a strikethrough line.

We can click on one deprecated term IRI:
http://www.ontobee.org/browser/rdf.php?o=ENVO&iri=http://purl.obolibrary.org/obo/ENVO_00000875
It also shows the term is deprecated in the annotation section:
[cid:image003.jpg@01D0CF88.01A692A0]

Please check them out and let us know if you have more comments and suggestions.

Thanks!

Edison and Oliver
