### ISSUE TITLE
VTO is out of date

### ISSUE THREAD

**Issue by balhoff** [OntoZoo/ontobee#49]
VTO has been update since the version shown in Ontobee. Could you please load the latest from here?

http://purl.obolibrary.org/obo/vto.owl

As of today, the latest version IRI is http://purl.obolibrary.org/obo/vto/2015-7-30/vto.owl

Thank you,
Jim

**Comment by yongqunh** [comment]
Updated:
http://www.ontobee.org/browser/index.php?o=VTO

Please check it out.

Oliver

**Comment by balhoff** [comment]
Looks great, thanks!
