### ISSUE TITLE
Ontobee suffers from https to http redirection error long ago fixed in OWLAPI, when loading ontologies

### ISSUE THREAD

**Issue by hoganwr** [OntoZoo/ontobee#52]
For several University of Florida Biomedical Informatics (UFBMI - see github.com/UFBMI) ontologies, Oliver reports back to us an error when they fail to load.

However, the error is not with our ontologies.  They all load fine in Protege versions 5.0 beta.

The error is a well-known http to https redirection error in older versions of the OWLAPI.  I have confirmed that this is indeed the case with James Overton who recognized the error as well.

I have attached screen prints from Protege 4.3 (http to https redirection error) and Protege 5.0 (ontology loads perfectly fine) to illustrate the issue.

Because we are all tending to move to GitHub, this issue is fairly severe, as GitHub uses https and we will be redirecting from PURLs that use http.

![screen shot 2015-10-16 at 3 52 46 pm](https://cloud.githubusercontent.com/assets/1253110/10552027/fba6098a-741e-11e5-99a2-400ca1dd9cdc.png)
![screen shot 2015-10-16 at 3 59 40 pm](https://cloud.githubusercontent.com/assets/1253110/10552028/fe3c53a2-741e-11e5-9135-dd795a87caf4.png)

**Comment by cmungall** [comment]
This is high priority. It should be easy to fix, just update to a new owlapi 3.5.x (note: updating to owlapi 4.x.x. will result in some incompatibilities. But this should not be necessary. Anything from the last year or two in the 3.x series is sufficient)

**Comment by yongqunh** [comment]
This issue is now resolved.
Edison eventually used the owlapi 4.x.x version and then made some update to solve the compatibility issue.
Please check out.
Oliver

**Comment by cmungall** [comment]
Thanks!
