### ISSUE TITLE
XAO is out of date

### ISSUE THREAD

**Issue by seger** [OntoZoo/ontobee#54]
The most recent XAO release was made on 27 May 2015. The ontology source shown in OntoBee is defunct. The repository is now located here: https://github.com/xenopus-anatomy/xao

**Comment by cmungall** [comment]
It should get the data from the OBO registry. Let me know if you need 
help Oliver

**Comment by e4ong1031** [comment]
XAO is now updated to the most recent version.

**Comment by cmungall** [comment]
Can you confirm that you're using the OBO registry and that ontology 
providers don't have to update things in two places?

**Comment by e4ong1031** [comment]
Yes, it is using an automated script to update XAO from the purl link provided by OBO registry. This maintenance script is implemented in beta version, and we will perform full update on all OBO registered ontologies after the transition to new Ontobee version.

**Comment by cmungall** [comment]
Thanks!
