### ISSUE TITLE
OntoBee shows property chain composition as pipes, which is misleading

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#56]
E.g.
http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002211

This is *really* misleading. A `|` looks like `OR`. The correct symbol is `o` which is composition

**Comment by e4ong1031** [comment]
Sorry for the confusion. The separator display is now changed from '|' to 'o'.
