### ISSUE TITLE
Term page doesn't load when ampersand in annotation value

### ISSUE THREAD

**Issue by balhoff** [OntoZoo/ontobee#61]
'camptotrichium' from Uberon:

http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_4400007

I think it is due to the '&' in the content of `rdfs:comment`:

>From Witten & Huysseune (2007): 'Two zones have been recognized in these camptotrichia: a superficial region of acellular fibrous bone, and a deep, mostly unmineralized, zone (Géraudie and Meunier 1982).'

The ontology is fine. I think it is a problem with escaping in the HTML generation in Ontobee.

cc @wdahdul

**Comment by e4ong1031** [comment]
Yes, it is the problem of not converting the '&' to Unicode and is resolved now.

Thanks.
