### ISSUE TITLE
issue loading GO?

### ISSUE THREAD

**Issue by mcourtot** [OntoZoo/ontobee#76]
There seem to be an issue with GO in that it is partly loaded only

Cellular component term is found: http://purl.obolibrary.org/obo/GO_0005575

But others (even old ones, created in 2009 for example) are not, such as http://purl.obolibrary.org/obo/GO_0085040
or
http://purl.obolibrary.org/obo/GO_0044219

Thanks,
Melanie

**Comment by e4ong1031** [comment]
The GO is re-loaded in GO. The two terms above are back now and I am closing this issue.. Please let me know if you still find missing terms and re-open this issue.

Thanks

**Comment by mcourtot** [comment]
Hi EDison,

Seems the same happened again:
http://purl.obolibrary.org/obo/GO_0005575

is a root term, cellular component, and doesn't resolve.

Thanks,
Melanie

**Comment by yongqunh** [comment]
It's due to a RDF triple store issue. Fixed now.

**Comment by mcourtot** [comment]
Thanks!
