### ISSUE TITLE
OBI doesn't seem to be loaded

### ISSUE THREAD

**Issue by mcourtot** [OntoZoo/ontobee#87]
As of Monday September 5th.

**Comment by yongqunh** [comment]
I just checked. It appears fine now:
http://www.ontobee.org/ontology/OBI
best,
Oliver

**Comment by mcourtot** [comment]
Oh, I see, I didn't realise the table was ordered by 'foundry' resources first, so I was looking at the wrong spot. Maybe arrange by alphabetical order by default, and then allow users to sort by using the headers?

**Comment by e4ong1031** [comment]
Oliver and I discussed and we re-arranged the ontologies by alphabetical order.

Thank you for the suggestion. I am closing this issue.
