### ISSUE TITLE
OntoBee version of PORO is stale

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#89]
http://www.ontobee.org/ontology/PORO

 versionIRI: http://purl.obolibrary.org/obo/poro/releases/2015-08-08/poro.owl 

in OLS:  Version: 2016-09-13 
http://www.ebi.ac.uk/ols/ontologies/poro

**Comment by cmungall** [comment]
Any update?

**Comment by e4ong1031** [comment]
Sorry, I forgot to reply you. The PORO was updated with verisonIRI http://purl.obolibrary.org/obo/poro/releases/2016-09-13/poro.owl.
