### ISSUE TITLE
CTENO is stale

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#92]
Compare: http://www.ebi.ac.uk/ols/ontologies/cteno

With: http://www.ontobee.org/ontology/CTENO

The ontobee one does not show a versionIRI. I believe this is a very out of date version in ontobee

**Comment by e4ong1031** [comment]
It is now updated.

 In addition, one of the import ontology file in CTENO does not link to a valid file, http://purl.obolibrary.org/obo/bspo.owl.

**Comment by cmungall** [comment]
Thanks! bspo url should be fixed soon.

It would be great if the ontobee load pipeline were more transparent, so we could see

 - when loads are scheduled
 - which loads failed
 - reason for failure (e.g. purl failure in dependent ontology)

I don't know how you do it at the moment, but I would recommend a CI system like Jenkins
