### ISSUE TITLE
Update Ontology metadata on Ontobee?

### ISSUE THREAD

**Issue by cooperl09** [OntoZoo/ontobee#95]
How do I update the metadata for the following ontologies:

http://www.ontobee.org/ontology/po
http://www.ontobee.org/ontology/to
http://www.ontobee.org/ontology/eo

Thanks,
Laurel

**Comment by cmungall** [comment]
My apologies, I told @cooperl09 to post here but this is an OBO problem.

Changes were made to the metadata file on Oct 7, e.g

https://github.com/OBOFoundry/OBOFoundry.github.io/commit/33f879c76fcb3f2add67210a0a96d7a7cbb55459#diff-08ee2f74b45c0bc9666572b216d0e304

However, a manual step by an OBO admin needs to be done to regenerate the metadata file. I will do this. This ticket can be closed
