### ISSUE TITLE
registry reload issue?

### ISSUE THREAD

**Issue by mcourtot** [OntoZoo/ontobee#98]
I created the DUO entry last week on the OBO Foundry table, and it has since been picked up and loved by OLS, but doesn't show up on Ontobee yet. I thought the reload was nightly, have there been recent issues?

**Comment by e4ong1031** [comment]
@mcourtot Thank you very much for raising the issue. It was a bug in the Ontobee script and is now fixed. I will monitor the auto-update process this week and make sure things are working fine.

**Comment by mcourtot** [comment]
Great, thanks Edison!
