### ISSUE TITLE
DDPHENO not updating

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#99]
http://www.ontobee.org/ontology/DDPHEN

is from May 2016

There have been multiple releases at the official PURL since then

OLS shows the latest which is available from the official PURL
http://www.ebi.ac.uk/ols/ontologies/ddpheno

**Comment by yongqunh** [comment]
It is probably due to some bug in the Ontobee automatic updating program.

Edison and I will take another close look tomorrow.

Oliver

**Comment by e4ong1031** [comment]
Similar #100 .

The auto-update pipeline successfully updates ontologies for three consecutive weeks. Will continue to monitor it.
